# Generated by Django 3.2.4 on 2021-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_OBS', '0002_alter_obs_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_model',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
