# Generated by Django 3.2.4 on 2021-07-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_OBS', '0003_obs_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obs_model',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
