# Generated by Django 3.2.4 on 2021-07-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_OBS', '0004_alter_obs_model_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obs_model',
            name='time_create',
        ),
        migrations.AddField(
            model_name='obs_model',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
