# Generated by Django 3.2.4 on 2021-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_OBS', '0005_auto_20210705_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_model',
            name='subtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obs_model',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
