# Generated by Django 3.2.4 on 2021-07-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_OBS', '0007_auto_20210712_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obs_model',
            old_name='name',
            new_name='slug',
        ),
    ]
